### ISSUE TITLE
Missing __init__.py in core folder

### ISSUE THREAD

**Issue by zPrototype** [mikey96/reflection-public#1]
Running the script currently throws the following error:
Traceback (most recent call last):
  File "reflection.py", line 6, in <module>
    import core.ThreadedStart as ThreadedStart
ModuleNotFoundError: No module named 'core.ThreadedStart'

This is because in reflection.py it's imported as core.ThreadedStart which works only if theres an __init__.py because this allows it to be included as a subpackage. Otherwise a quick dirty fix is changing the import to:
sys.path.insert(1, '/opt/reflection-public/core')
import ThreadedStart as ThreadedStart

Then we are faced with the next error:
Traceback (most recent call last):
  File "reflection.py", line 6, in <module>
    import ThreadedStart as ThreadedStart
  File "/opt/reflection-public/core/ThreadedStart.py", line 6, in <module>
    import core.XSSRequest as xss
ModuleNotFoundError: No module named 'core.XSSRequest'

Here we need to remove the suffix "core." in the imports since the files all are in the same directory anyway. This needs to be done for all files in the "core" directory.

Now we get one last import error, in the SSRFRequest.py we need to change the following import "from core import ParseParams" to -> import ParseParams

Now everything works.

**Comment by mikey96** [comment]
Thanks,  I actually had another user bring up this issue to me about 30 minutes ago. I am going to fix it, however they were able to remediate the issue by update python from 3.6 to the latest version - just in case anyone else sees. It is a simple fix for now.

**Comment by zPrototype** [comment]
I'm running python 3.9 sorry forgot to mention that.

**Comment by mikey96** [comment]
Thanks, I appreciate it going to push the fixes later tonight for this issue :)
